name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install
        run: npm install
      - name: Lerna bootstrap
        run: npm run bootstrap
      - name: linting
        run: npm run lint
      - name: testing
        run: npm run test
